### ISSUE TITLE
Catch2

### ISSUE THREAD

**Issue by mjsyts** [midouest/bytebeat#4]
```catch2/catch.hpp``` no longer exists. I tried updating the includes to ```catch_all.hpp``` but this causes a linker fail.

Is Catch2 necessary if I just want to use the plugin?

**Comment by midouest** [comment]
Catch2 is not necessary to use the plugin. Unfortunately, you will have to manually install the plugin as the `install` target depends on the tests.

You should be able to build just the plugin with:

```bash
cmake --build build --target ByteBeat_scsynth
```

That will create the ByteBeat_scsynth.scx file in the build/ folder.

Then you'll need to copy the appropriate files to the SuperCollider extensions folder according to [Using Extensions](https://doc.sccode.org/Guides/UsingExtensions.html).

```
~Library/ApplicationSupport/SuperCollider/Extensions/ByteBeat
└── ByteBeat
    ├── ByteBeat_scsynth.scx
    ├── Classes
    │   ├── ByteBeat.sc
    │   └── ByteBeatController.sc
    └── HelpSource
        └── Classes
            ├── ByteBeat.schelp
            └── ByteBeatController.schelp
```

I'll look into the Catch2 header issue. Thanks for the report!

**Comment by midouest** [comment]
Should be fixed!

**Comment by mjsyts** [comment]
Awesome, it’s working now! Is it possible to run it at server sample rate? I am getting errors when I try. It’s fine at normal ByteBeat rate (8K) but if I try something like SampleRate.ir or 44100 it doesn’t work.

M. Josiah Sytsma
Composer, Saxophonist, Educator, Repair Tech
***@***.***
https://josiahsytsma.hearnow.com/
https://github.com/mjsyts

**Comment by midouest** [comment]
Can you open a new issue with the errors that you're seeing? SampleRate.ir and 44100hz are working for me.

**Comment by mjsyts** [comment]
It does work, never mind. I had to use Sweep.ar(1, SampleRate.ir), then set the index accordingly. PulseCount/Impulse will only go up to the Nyquist frequency.

M. Josiah Sytsma
Composer, Saxophonist, Educator, Repair Tech
***@***.***
https://josiahsytsma.hearnow.com/
https://github.com/mjsyts
